[versions]
libautoupdate = "1.3.1"
moulconfig = "4.2.0-beta"
jbAnnotations = "24.1.0"

hypixelmodapi = "1.0.1"
hypixelmodapi_fabric = "1.0.1+build.1+mc1.21"

fabricLanguageKotlin = "1.13.7+kotlin.2.2.21"

roughlyenoughitems = "19.0.806"

[libraries]
moulconfig = { module = "org.notenoughupdates.moulconfig:legacy", version.ref = "moulconfig" }
libautoupdate = { module = "moe.nea:libautoupdate", version.ref = "libautoupdate" }
jbAnnotations = { module = "org.jetbrains:annotations", version.ref = "jbAnnotations" }
autoservice_ksp = {module="dev.zacsweers.autoservice:auto-service-ksp",version="1.1.0"}
autoservice_annotations = {module="com.google.auto.service:auto-service-annotations",version="1.1.1"}

hypixelmodapi = { module = "net.hypixel:mod-api", version.ref = "hypixelmodapi" }
hypixelmodapi_fabric = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelmodapi_fabric" }

fabricLanguageKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricLanguageKotlin" }

roughlyenoughitems = { module = "me.shedaniel:RoughlyEnoughItems-api-fabric", version.ref = "roughlyenoughitems" }
